'use strict';
/**
 * Seed data.
 *  seedMinimal – a clean business with one owner account (for real deployments).
 *  seedDemo    – "Greenfield Supermarket", Lagos: 3 locations, 4 registers, staff in every role,
 *                ~55 products, customers, and ~10 days of trading history generated by driving the
 *                real services (sessions, sales, payments, refunds, settlements, payouts, reconciliation),
 *                so every figure in the demo is internally consistent.
 */
const { newId, nowIso, setClock } = require('../lib/ids');
const { hashSecret, randomToken } = require('../lib/crypto');
const { ROLE_TEMPLATES, PERMISSIONS } = require('../services/permissions');
const { localDate, localMidnightUtc, addDays } = require('../lib/time');

function ean13(body12) {
  const d = body12.split('').map(Number);
  const sum = d.reduce((a, x, i) => a + x * (i % 2 ? 3 : 1), 0);
  return body12 + ((10 - (sum % 10)) % 10);
}

function baseBusiness(app, { name, currency = 'NGN', timezone = 'Africa/Lagos', locale = 'en-NG' }) {
  const { db } = app;
  const now = nowIso();
  const bid = newId('biz');
  db.run(`INSERT INTO businesses (id,name,currency,currency_minor,locale,timezone,prices_include_tax,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)`, bid, name, currency, 2, locale, timezone, 1, now, now);
  for (const [code, cat, desc] of PERMISSIONS) db.run('INSERT OR IGNORE INTO permissions (code, category, description) VALUES (?,?,?)', code, cat, desc);
  const roles = {};
  for (const t of ROLE_TEMPLATES) {
    const id = newId('rol');
    db.run('INSERT INTO roles (id,business_id,code,name,description,max_discount_pct,is_system,created_at) VALUES (?,?,?,?,?,?,?,?)', id, bid, t.code, t.name, t.description, t.max_discount_pct, 1, now);
    for (const p of t.permissions) db.run('INSERT INTO role_permissions (role_id, permission_code) VALUES (?,?)', id, p);
    roles[t.code] = id;
  }
  return { bid, roles };
}

function addUser(app, bid, { username, full_name, role, password, pin, location, email, phone, mustChange = 0 }) {
  const id = newId('usr'); const now = nowIso();
  app.db.run(`INSERT INTO users (id,business_id,username,full_name,email,phone,password_hash,pin_hash,role_id,home_location_id,is_active,must_change_password,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    id, bid, username, full_name, email || null, phone || null, hashSecret(password), pin ? hashSecret(pin) : null, role, location || null, 1, mustChange, now, now);
  return id;
}

function addPaymentMethod(app, bid, m, sort) {
  app.db.run(`INSERT INTO payment_methods (id,business_id,code,name,type,provider_code,is_active,allow_offline,allow_change,requires_reference,sort_order,shortcut,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    newId('pmt'), bid, m.code, m.name, m.type, m.provider, 1, m.offline ? 1 : 0, m.type === 'cash' ? 1 : 0, m.provider === 'manual' ? 1 : 0, sort, m.shortcut || null, nowIso());
}

function seedMinimal(app) {
  const { db } = app;
  db.tx(() => {
    const { bid, roles } = baseBusiness(app, { name: 'My Business' });
    const loc = newId('loc');
    db.run('INSERT INTO locations (id,business_id,code,name,type,created_at) VALUES (?,?,?,?,?,?)', loc, bid, 'MAIN', 'Main store', 'store', nowIso());
    db.run('INSERT INTO registers (id,location_id,code,name,created_at) VALUES (?,?,?,?,?)', newId('reg'), loc, 'R01', 'Register 1', nowIso());
    db.run('INSERT INTO tax_rates (id,business_id,code,name,rate_bp,created_at) VALUES (?,?,?,?,?,?)', newId('tax'), bid, 'STD', 'Standard', 0, nowIso());
    addPaymentMethod(app, bid, { code: 'cash', name: 'Cash', type: 'cash', provider: 'cash', offline: true, shortcut: 'F8' }, 1);
    const pw = process.env.POS_OWNER_PASSWORD || `Setup${randomToken(4).replace(/[^A-Za-z0-9]/g, '')}9`;
    addUser(app, bid, { username: 'owner', full_name: 'Business Owner', role: roles.owner, password: pw, location: loc, mustChange: 1 });
    app.log('info', `Initial owner account: username "owner", password "${pw}" (must be changed at first sign-in)`);
  });
}

// ─────────────────────────────── demo ───────────────────────────────
const CATS = ['Grains & Staples', 'Beverages', 'Dairy & Eggs', 'Bakery', 'Fresh Produce', 'Meat & Frozen', 'Snacks & Confectionery', 'Household & Cleaning', 'Personal Care', 'Baby Care', 'Wines & Spirits', 'Canned & Pantry'];
// [name, category, brand, unit, price ₦, cost ₦, tax, min, stock, extra]
const PRODUCTS = [
  ['Mama Gold Rice 5kg', 0, 'Mama Gold', 'each', 12500, 10900, 'EX', 15, 80],
  ['Royal Stallion Rice 10kg', 0, 'Royal Stallion', 'each', 24800, 21700, 'EX', 10, 45],
  ['Golden Penny Semovita 1kg', 0, 'Golden Penny', 'each', 2100, 1780, 'EX', 20, 120],
  ['Honeywell Wheat Meal 1kg', 0, 'Honeywell', 'each', 2300, 1950, 'EX', 20, 90],
  ['Dangote Spaghetti 500g', 0, 'Dangote', 'each', 1150, 950, 'EX', 40, 300],
  ['Golden Penny Spaghetti 500g', 0, 'Golden Penny', 'each', 1200, 990, 'EX', 40, 260],
  ['Indomie Chicken Noodles 70g', 0, 'Indomie', 'each', 300, 245, 'EX', 200, 1600, { pack: 40 }],
  ['Honey Beans (Oloyin) 1kg', 0, null, 'each', 3400, 2900, 'EX', 15, 70],
  ['Garri Ijebu 2kg', 0, null, 'each', 2800, 2300, 'EX', 15, 60],
  ['Coca-Cola 50cl PET', 1, 'Coca-Cola', 'each', 500, 390, 'VAT', 96, 720, { pack: 12 }],
  ['Fanta Orange 50cl PET', 1, 'Fanta', 'each', 500, 390, 'VAT', 96, 540, { pack: 12 }],
  ['Eva Table Water 75cl', 1, 'Eva', 'each', 300, 220, 'VAT', 120, 900, { pack: 12 }],
  ['Chivita 100% Orange Juice 1L', 1, 'Chivita', 'each', 2600, 2150, 'VAT', 24, 140],
  ['Nescafé Classic 200g', 1, 'Nescafé', 'each', 6800, 5750, 'VAT', 10, 40],
  ['Milo Refill 500g', 1, 'Nestlé', 'each', 4900, 4100, 'VAT', 20, 85],
  ['Cadbury Bournvita Refill 500g', 1, 'Cadbury', 'each', 4300, 3600, 'VAT', 20, 70],
  ['Lipton Yellow Label Tea 100 bags', 1, 'Lipton', 'each', 2700, 2250, 'VAT', 15, 60],
  ['Malta Guinness Can 33cl', 1, 'Guinness', 'each', 650, 520, 'VAT', 48, 360, { pack: 24 }],
  ['Peak Evaporated Milk 160g', 2, 'Peak', 'each', 650, 540, 'VAT', 48, 400],
  ['Peak Full Cream Milk Powder 400g', 2, 'Peak', 'each', 5600, 4750, 'VAT', 15, 75],
  ['Three Crowns Milk 160g', 2, 'Three Crowns', 'each', 550, 450, 'VAT', 48, 300],
  ['Hollandia Yoghurt Strawberry 1L', 2, 'Hollandia', 'each', 2900, 2420, 'VAT', 20, 18],
  ['Eggs — Crate of 30', 2, null, 'each', 6200, 5400, 'EX', 10, 40],
  ['Blue Band Margarine 450g', 2, 'Blue Band', 'each', 2400, 2000, 'VAT', 15, 60],
  ['Family Sliced Bread 800g', 3, 'Greenfield Bakery', 'each', 1800, 1450, 'EX', 20, 70],
  ['Butter Croissant', 3, 'Greenfield Bakery', 'each', 900, 600, 'EX', 10, 35],
  ['Tomatoes', 4, null, 'kg', 2500, 1900, 'EX', 10, 60, { plu: '10001' }],
  ['Red Onions', 4, null, 'kg', 1800, 1350, 'EX', 10, 55, { plu: '10002' }],
  ['Irish Potatoes', 4, null, 'kg', 2200, 1700, 'EX', 10, 50, { plu: '10003' }],
  ['Ripe Plantain (each)', 4, null, 'each', 600, 430, 'EX', 30, 140],
  ['Pineapple (each)', 4, null, 'each', 1500, 1100, 'EX', 10, 45],
  ['Beef — Boneless', 5, null, 'kg', 7500, 6200, 'EX', 8, 40, { plu: '20001' }],
  ['Whole Chicken (Frozen)', 5, null, 'kg', 5800, 4750, 'EX', 8, 45, { plu: '20002' }],
  ['Titus Mackerel (Frozen)', 5, 'Titus', 'kg', 4200, 3450, 'EX', 8, 38, { plu: '20003' }],
  ['Pringles Original 165g', 6, 'Pringles', 'each', 3900, 3200, 'VAT', 12, 50],
  ["McVitie's Digestive 400g", 6, "McVitie's", 'each', 2500, 2050, 'VAT', 12, 55],
  ['Gala Sausage Roll', 6, 'UAC', 'each', 300, 240, 'VAT', 60, 400, { pack: 24 }],
  ['Cabin Biscuit 350g', 6, 'Cabin', 'each', 500, 400, 'VAT', 30, 180],
  ['Kinder Joy', 6, 'Ferrero', 'each', 1400, 1120, 'VAT', 24, 9],
  ['Hypo Bleach 1L', 7, 'Hypo', 'each', 1300, 1050, 'VAT', 20, 90],
  ['Ariel Detergent 900g', 7, 'Ariel', 'each', 3300, 2750, 'VAT', 20, 80],
  ['Morning Fresh Dishwash 400ml', 7, 'Morning Fresh', 'each', 1500, 1200, 'VAT', 20, 85],
  ['Harpic Toilet Cleaner 500ml', 7, 'Harpic', 'each', 2200, 1800, 'VAT', 12, 50],
  ['Rose Plus Toilet Tissue 10 rolls', 7, 'Rose Plus', 'each', 3800, 3150, 'VAT', 15, 65],
  ['Raid Multi-Insect Killer 300ml', 7, 'Raid', 'each', 3100, 2580, 'VAT', 12, 7],
  ['Close-Up Toothpaste 140g', 8, 'Close-Up', 'each', 1200, 960, 'VAT', 24, 120],
  ['Dettol Soap 110g', 8, 'Dettol', 'each', 900, 720, 'VAT', 36, 150],
  ['Nivea Body Lotion 400ml', 8, 'Nivea', 'each', 6500, 5400, 'VAT', 8, 30],
  ['Always Ultra Pads (8)', 8, 'Always', 'each', 1700, 1380, 'VAT', 24, 90],
  ['Pampers Premium Care Size 3 (58)', 9, 'Pampers', 'each', 21500, 18600, 'VAT', 6, 24],
  ['Cerelac Wheat 400g', 9, 'Nestlé', 'each', 4500, 3780, 'VAT', 10, 40],
  ['Andre Rosé 750ml', 10, 'Andre', 'each', 9500, 8000, 'VAT', 6, 30, { age: 1 }],
  ['Four Cousins Sweet Red 750ml', 10, 'Four Cousins', 'each', 8200, 6900, 'VAT', 6, 36, { age: 1 }],
  ['Star Lager Can 33cl', 10, 'Star', 'each', 750, 600, 'VAT', 48, 300, { age: 1, pack: 24 }],
  ['Titus Sardines 125g', 11, 'Titus', 'each', 1100, 880, 'VAT', 36, 200],
  ['Gino Tomato Paste 210g', 11, 'Gino', 'each', 700, 560, 'VAT', 48, 260],
  ['Kings Vegetable Oil 3L', 11, 'Kings', 'each', 9800, 8600, 'VAT', 10, 50],
  ['Dangote Sugar 500g', 11, 'Dangote', 'each', 1300, 1060, 'VAT', 30, 150],
  ['Dangote Salt 500g', 11, 'Dangote', 'each', 400, 310, 'VAT', 30, 140],
  ['Knorr Chicken Cubes (50)', 11, 'Knorr', 'each', 2200, 1820, 'VAT', 20, 100],
];
const CUSTOMERS = [
  ['Ngozi Adeyemi', '+2348031234501'], ['Babajide Ogunleye', '+2348052234502'], ['Fatima Bello', '+2348063234503'], ['Emeka Nwosu', '+2348074234504'],
  ['Kemi Adebayo', '+2348085234505'], ['Ibrahim Musa', '+2348096234506'], ['Chiamaka Obi', '+2349017234507'], ['Oluwaseun Akinola', '+2349028234508'],
  ['Hauwa Abubakar', '+2349039234509'], ['Tobi Fashola', '+2347040234510'], ['Uche Okonkwo', '+2347051234511'], ['Yetunde Lawal', '+2347062234512'],
  ['Segun Adewale', '+2348133234513'], ['Amaka Eze', '+2348144234514'], ['Musa Danjuma', '+2348155234515'], ['Bisi Olatunji', '+2348166234516'],
  ['Kelechi Ibe', '+2348177234517'], ['Zainab Yusuf', '+2348188234518'], ['Femi Oladipo', '+2348199234519'], ['Adaora Chukwu', '+2348100234520'],
];

function mulberry32(a) { return () => { a |= 0; a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }

function seedDemo(app, { days = 10 } = {}) {
  const { db } = app;
  const rnd = mulberry32(20260926);
  const pick = (arr) => arr[Math.floor(rnd() * arr.length)];
  db.exec('PRAGMA synchronous = OFF');
  const tz = 'Africa/Lagos';
  const realNow = new Date();
  let cursor = new Date(localMidnightUtc(addDays(localDate(realNow, tz), -days), tz).getTime() - 3 * 86400000);
  setClock(() => cursor);
  const at = (d) => { cursor = d; };

  let bid; let roles; const loc = {}; const reg = {}; const users = {}; const tax = {}; const cats = []; const products = [];
  db.tx(() => {
    ({ bid, roles } = baseBusiness(app, { name: 'Greenfield Supermarket' }));
    db.run(`UPDATE businesses SET legal_name=?, tax_id=?, address=?, phone=?, email=?, website=? WHERE id=?`,
      'Greenfield Supermarket Ltd', '12345678-0001', '14 Admiralty Way, Lekki Phase 1, Lagos', '+234 1 700 0000', 'hello@greenfield.example', 'greenfield.example', bid);
    const L = [['LEK', 'Lekki Phase 1', 'store', '14 Admiralty Way, Lekki Phase 1, Lagos', '+234 1 700 0001'], ['IKJ', 'Ikeja GRA', 'store', '22 Isaac John St, Ikeja GRA, Lagos', '+234 1 700 0002'], ['WHS', 'Central Warehouse', 'warehouse', 'Plot 5, Oregun Industrial Estate, Lagos', null]];
    for (const [code, name, type, address, phone] of L) { loc[code] = newId('loc'); db.run('INSERT INTO locations (id,business_id,code,name,type,address,phone,created_at) VALUES (?,?,?,?,?,?,?,?)', loc[code], bid, code, name, type, address, phone, nowIso()); }
    for (const [l, code, name] of [['LEK', 'R01', 'Lane 1'], ['LEK', 'R02', 'Lane 2'], ['LEK', 'R03', 'Lane 3 (Express)'], ['IKJ', 'R01', 'Lane 1']]) {
      const id = newId('reg'); reg[`${l}-${code}`] = id; db.run('INSERT INTO registers (id,location_id,code,name,created_at) VALUES (?,?,?,?,?)', id, loc[l], code, name, nowIso());
    }
    tax.VAT = newId('tax'); tax.EX = newId('tax');
    db.run('INSERT INTO tax_rates (id,business_id,code,name,rate_bp,created_at) VALUES (?,?,?,?,?,?)', tax.VAT, bid, 'VAT', 'VAT 7.5%', 750, nowIso());
    db.run('INSERT INTO tax_rates (id,business_id,code,name,rate_bp,created_at) VALUES (?,?,?,?,?,?)', tax.EX, bid, 'EXEMPT', 'VAT exempt (basic food)', 0, nowIso());
    for (const c of CATS) { const id = newId('cat'); cats.push(id); db.run('INSERT INTO categories (id,business_id,name,created_at) VALUES (?,?,?,?)', id, bid, c, nowIso()); }
    const sup = {};
    for (const [n, c, p] of [['Nestlé Nigeria Distribution', 'Order desk', '+2348001110001'], ['Dangote Foods Depot', 'Sales rep', '+2348001110002'], ['Lagos Fresh Farms Co-op', 'Mrs Ade', '+2348001110003'], ['Unilever Trade Partners', 'Account manager', '+2348001110004'], ['Coca-Cola HBC Nigeria', 'Key accounts', '+2348001110005']]) {
      sup[n] = newId('sup'); db.run('INSERT INTO suppliers (id,business_id,name,contact_name,phone,created_at) VALUES (?,?,?,?,?,?)', sup[n], bid, n, c, p, nowIso());
    }
    const supFor = (cat, brand) => (['Nestlé', 'Peak', 'Milo'].includes(brand) || cat === 9 ? sup['Nestlé Nigeria Distribution'] : ['Dangote', 'Golden Penny', 'Mama Gold'].includes(brand) ? sup['Dangote Foods Depot']
      : [4, 5].includes(cat) ? sup['Lagos Fresh Farms Co-op'] : ['Coca-Cola', 'Fanta', 'Eva'].includes(brand) ? sup['Coca-Cola HBC Nigeria'] : sup['Unilever Trade Partners']);

    PRODUCTS.forEach(([name, cat, brand, unit, price, cost, tx, min, stock, extra = {}], i) => {
      const id = newId('prd'); const now = nowIso();
      const sku = `${CATS[cat].replace(/[^A-Z]/g, '').slice(0, 2)}${String(1001 + i)}`;
      db.run(`INSERT INTO products (id,business_id,sku,name,category_id,brand,unit,is_weighed,plu,price,cost,tax_rate_id,min_stock,reorder_qty,supplier_id,age_restricted,created_at,updated_at)
              VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, id, bid, sku, name, cats[cat], brand, unit, extra.plu ? 1 : 0, extra.plu || null, price * 100, cost * 100, tax[tx], min, min * 2, supFor(cat, brand), extra.age ? 1 : 0, now, now);
      if (!extra.plu) {
        db.run('INSERT INTO product_barcodes (id,business_id,product_id,barcode,pack_qty,is_primary,created_at) VALUES (?,?,?,?,?,?,?)', newId('bar'), bid, id, ean13(`615${String(4000000 + i * 137).padStart(9, '0')}`), 1, 1, now);
        if (extra.pack) db.run('INSERT INTO product_barcodes (id,business_id,product_id,barcode,pack_qty,is_primary,created_at) VALUES (?,?,?,?,?,?,?)', newId('bar'), bid, id, ean13(`615${String(8000000 + i * 137).padStart(9, '0')}`), extra.pack, 0, now);
      }
      products.push({ id, name, unit, price: price * 100, weighed: !!extra.plu, plu: extra.plu, age: !!extra.age, stock, cat });
    });

    const methods = [
      { code: 'cash', name: 'Cash', type: 'cash', provider: 'cash', offline: true, shortcut: 'F8' },
      { code: 'card', name: 'Card (integrated terminal)', type: 'card', provider: 'sim-card', shortcut: 'F9' },
      { code: 'transfer', name: 'Bank transfer', type: 'bank_transfer', provider: 'sim-transfer', shortcut: 'F10' },
      { code: 'mobile', name: 'Mobile money / USSD', type: 'mobile_money', provider: 'sim-wallet' },
      { code: 'ext_pos', name: 'Card (standalone POS)', type: 'card', provider: 'manual', offline: true },
      { code: 'voucher', name: 'Gift voucher', type: 'other', provider: 'manual', offline: true },
    ];
    methods.forEach((m, i) => addPaymentMethod(app, bid, m, i + 1));
    for (const [code, name, cfg] of [['sim-card', 'Simulated card terminal (TEST)', { kind: 'card', scenario: 'auto_approve', delay_ms: 2500, terminal_id: 'SIM-LEK-01' }],
      ['sim-transfer', 'Simulated bank transfer (TEST)', { kind: 'bank_transfer', scenario: 'await_customer' }], ['sim-wallet', 'Simulated mobile money (TEST)', { kind: 'mobile_money', scenario: 'await_customer' }]]) {
      const ref = `provider:${bid}:${code}:${randomToken(6)}`;
      app.secrets.set(ref, randomToken(24));
      db.run('INSERT INTO provider_configs (id,business_id,provider_code,display_name,mode,is_active,config_json,secret_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)', newId('pvc'), bid, code, name, 'test', 1, JSON.stringify(cfg), ref, nowIso(), nowIso());
    }
    for (const [code, name, type, pc, extra] of [['SAFE-LEK', 'Lekki store safe', 'cash_safe', null, { location: loc.LEK }], ['SAFE-IKJ', 'Ikeja store safe', 'cash_safe', null, { location: loc.IKJ }],
      ['BANK-OPS', 'Operating account', 'bank', null, { bank: 'Example Bank', mask: '4821' }], ['BAL-CARD', 'Card provider balance', 'provider_balance', 'sim-card', {}],
      ['BAL-TRF', 'Transfer provider balance', 'provider_balance', 'sim-transfer', {}], ['BAL-MOB', 'Mobile money balance', 'provider_balance', 'sim-wallet', {}]]) {
      db.run('INSERT INTO financial_accounts (id,business_id,code,name,type,provider_code,location_id,bank_name,account_mask,currency,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', newId('fac'), bid, code, name, type, pc, extra.location || null, extra.bank || null, extra.mask || null, 'NGN', nowIso());
    }

    const staff = [
      ['owner', 'Adaeze Okafor', 'owner', '2580'], ['manager', 'Tunde Bakare', 'manager', '4826'], ['supervisor', 'Grace Eze', 'supervisor', '3791'],
      ['cashier1', 'Chinedu Obi', 'cashier', '1470'], ['cashier2', 'Aisha Mohammed', 'cashier', '2690'], ['cashier3', 'Samuel Johnson', 'cashier', '3058'],
      ['stock', 'Emeka Nnaji', 'inventory', '5913'], ['finance', 'Funmilayo Adeyemi', 'finance', '7342'],
    ];
    for (const [u, n, r, pin] of staff) users[u] = addUser(app, bid, { username: u, full_name: n, role: roles[r], password: 'demo1234', pin, location: loc.LEK, email: `${u}@greenfield.example` });

    const settings = { 'receipt.footer': 'Thank you for shopping at Greenfield! Returns within 30 days with receipt.', 'loyalty.enabled': true, 'loyalty.points_per_currency_unit': 0.01, 'receipt.header': 'Fresh food. Fair prices.', 'system.demo_mode': true };
    for (const [k, val] of Object.entries(settings)) db.run('INSERT INTO settings (business_id,key,value_json,updated_at) VALUES (?,?,?,?)', bid, k, JSON.stringify(val), nowIso());
  });
  app.settings.invalidate(bid);

  const ctxFor = (u, regKey) => {
    const user = db.get('SELECT * FROM users WHERE id = ?', users[u]);
    const role = db.get('SELECT * FROM roles WHERE id = ?', user.role_id);
    return { user, role, perms: app.auth.rolePerms(role.id), businessId: bid, registerId: regKey ? reg[regKey] : null };
  };
  const owner = ctxFor('owner');

  // opening stock at every location
  db.tx(() => {
    for (const p of products) {
      app.inventory.move(owner, { productId: p.id, locationId: loc.LEK, type: 'opening', qty: p.stock, reason: 'Opening stock (go-live count)', referenceType: 'product', referenceId: p.id });
      app.inventory.move(owner, { productId: p.id, locationId: loc.IKJ, type: 'opening', qty: Math.round(p.stock * 0.6), reason: 'Opening stock (go-live count)', referenceType: 'product', referenceId: p.id });
      app.inventory.move(owner, { productId: p.id, locationId: loc.WHS, type: 'opening', qty: p.stock * 3, reason: 'Opening stock (go-live count)', referenceType: 'product', referenceId: p.id });
    }
    for (const [n, ph] of CUSTOMERS) app.customers.create(owner, { full_name: n, phone: ph, marketing_consent: rnd() < 0.5 });
  });
  const customers = db.all('SELECT id FROM customers WHERE business_id = ?', bid).map((c) => c.id);

  // popularity weights
  const weights = products.map((p) => (p.price < 100000 ? 6 : p.price < 500000 ? 3 : 1) * (p.age ? 0.5 : 1));
  const wsum = weights.reduce((a, b) => a + b, 0);
  const pickProduct = () => { let r = rnd() * wsum; for (let i = 0; i < products.length; i++) { r -= weights[i]; if (r <= 0) return products[i]; } return products[0]; };
  const sim = (code) => app.payments.buildProvider(bid, code);

  async function ringSale(ctx, when, { discount = false } = {}) {
    at(when);
    const saleId = app.sales.create(ctx);
    const lines = 1 + Math.floor(rnd() * rnd() * 12);
    for (let i = 0; i < lines; i++) {
      const p = pickProduct();
      cursor = new Date(cursor.getTime() + 4000 + rnd() * 9000);
      if (p.weighed) app.sales.addItem(ctx, saleId, { product_id: p.id, weight: Math.round((0.4 + rnd() * 2) * 1000) / 1000 });
      else app.sales.addItem(ctx, saleId, { product_id: p.id, qty: rnd() < 0.2 ? 2 + Math.floor(rnd() * 3) : 1, age_verified: p.age });
    }
    if (rnd() < 0.3) app.sales.setCustomer(ctx, saleId, { customer_id: pick(customers) });
    if (discount) app.sales.setCartDiscount(ctx, saleId, { type: 'percent', value: 5, reason: 'Loyalty week promo' });
    let sale = app.sales.get(ctx, saleId);
    cursor = new Date(cursor.getTime() + 20000);
    const r = rnd();
    const key = () => `seed-${randomToken(10)}`;
    if (r < 0.46) {
      const tender = sale.total <= 100000 ? Math.ceil(sale.total / 50000) * 50000 : Math.ceil(sale.total / 100000) * 100000;
      await app.payments.create(ctx, saleId, { method_code: 'cash', tendered: rnd() < 0.3 ? sale.total : tender, idempotency_key: key() });
    } else if (r < 0.64) {
      await app.payments.create(ctx, saleId, { method_code: 'ext_pos', amount: sale.total, reference: String(100000 + Math.floor(rnd() * 899999)), idempotency_key: key() });
    } else if (r < 0.95) {
      const code = r < 0.84 ? 'card' : r < 0.92 ? 'transfer' : 'mobile';
      const pc = code === 'card' ? 'sim-card' : code === 'transfer' ? 'sim-transfer' : 'sim-wallet';
      const res = await app.payments.create(ctx, saleId, { method_code: code, amount: sale.total, idempotency_key: key() });
      cursor = new Date(cursor.getTime() + 15000);
      const out = sim(pc).simulate(res.payment.provider_ref, 'approve');
      app.payments.handleWebhook(pc, out.webhook.headers, out.webhook.body, bid);
    } else {
      const part = Math.min(sale.total - 100, Math.round(sale.total / 200000) * 100000 || 50000);
      if (part > 0 && part < sale.total) {
        await app.payments.create(ctx, saleId, { method_code: 'cash', tendered: part, idempotency_key: key() });
        sale = app.sales.get(ctx, saleId);
        const res = await app.payments.create(ctx, saleId, { method_code: 'card', amount: sale.balance_due, idempotency_key: key() });
        const out = sim('sim-card').simulate(res.payment.provider_ref, 'approve');
        app.payments.handleWebhook('sim-card', out.webhook.headers, out.webhook.body, bid);
      } else {
        await app.payments.create(ctx, saleId, { method_code: 'cash', tendered: sale.total, idempotency_key: key() });
      }
    }
    return saleId;
  }

  const runDay = async (dayYmd, { isToday = false } = {}) => {
    const dayStart = localMidnightUtc(dayYmd, tz).getTime();
    const lanes = [['LEK-R01', 'cashier1'], ['LEK-R02', 'cashier2'], ['IKJ-R01', 'cashier3']];
    const dow = new Date(`${dayYmd}T12:00:00Z`).getUTCDay();
    const saleIds = [];
    for (const [laneKey, cashier] of lanes) {
      if (isToday && laneKey !== 'LEK-R02') continue;
      const ctx = ctxFor(cashier, laneKey);
      const openAt = new Date(dayStart + (8 * 60 + Math.floor(rnd() * 20)) * 60000);
      const closeAt = new Date(dayStart + (20 * 60 + 30 + Math.floor(rnd() * 30)) * 60000);
      const end = isToday ? new Date(Math.min(closeAt.getTime(), realNow.getTime() - 10 * 60000)) : closeAt;
      if (end <= openAt) continue;
      at(openAt);
      const session = app.sessions.open(ctx, { opening_float: 5000000 });
      const base = (laneKey.startsWith('IKJ') ? 18 : 30) * (dow === 6 || dow === 0 ? 1.4 : 1);
      const n = Math.round(base * ((end - openAt) / (closeAt - openAt)) * (0.85 + rnd() * 0.3));
      const times = Array.from({ length: n }, () => openAt.getTime() + rnd() * (end - openAt - 120000)).sort((a, b) => a - b);
      for (const t of times) {
        const id = await ringSale(ctx, new Date(t), { discount: rnd() < 0.03 });
        saleIds.push({ id, ctx, t });
        // cash drop when drawer gets heavy
        const f = app.sessions.figures(session.id);
        if (f.expected_cash > 30000000) { cursor = new Date(cursor.getTime() + 60000); app.sessions.cashMovement(ctx, { type: 'cash_drop', amount: 20000000, reason: 'Safe drop', override: { username: 'supervisor', pin: '3791' } }); }
      }
      // a paid-out for supplies once in a while
      if (rnd() < 0.3 && !isToday) { cursor = new Date(cursor.getTime() + 60000); app.sessions.cashMovement(ctx, { type: 'paid_out', amount: 350000, reason: 'Cleaning supplies (petty cash)', reference: 'PC-receipt', override: { username: 'supervisor', pin: '3791' } }); }
      // one same-session void per couple of days
      if (!isToday && rnd() < 0.5 && saleIds.length > 3) {
        const v = saleIds[saleIds.length - 2];
        if (v.ctx === ctx) {
          cursor = new Date(cursor.getTime() + 60000);
          const s = db.get('SELECT status FROM sales WHERE id = ?', v.id);
          const pays = db.all(`SELECT method_type FROM payments WHERE sale_id = ? AND status = 'succeeded'`, v.id);
          if (s.status === 'completed' && pays.every((p) => p.method_type === 'cash')) {
            await app.refunds.void(ctx, v.id, { reason_note: 'Customer changed mind at till', idempotency_key: `seed-void-${v.id}`, override: { username: 'supervisor', pin: '3791' } });
          }
        }
      }
      if (!isToday) {
        at(closeAt);
        const f = app.sessions.figures(session.id);
        const roll = rnd();
        const variance = roll < 0.75 ? 0 : roll < 0.9 ? -50000 : roll < 0.97 ? 20000 : -1200000;
        app.sessions.close(ctx, session.id, { counted_cash: f.expected_cash + variance, note: variance ? 'Counted twice' : null });
      }
    }
    return saleIds;
  };

  return (async () => {
    const today = localDate(realNow, tz);
    const allSales = [];
    for (let i = days; i >= 1; i--) allSales.push(...(await runDay(addDays(today, -i))));

    // goods receipt mid-history + a few stock adjustments
    at(new Date(localMidnightUtc(addDays(today, -4), tz).getTime() + 7 * 3600000));
    const stockCtx = ctxFor('stock');
    const low = products.filter((p) => !p.weighed).slice(0, 8);
    app.inventory.receive(stockCtx, { location_id: loc.LEK, supplier_id: db.value('SELECT id FROM suppliers WHERE name = ?', 'Dangote Foods Depot'), supplier_ref: 'INV-DFD-88213', items: low.map((p) => ({ product_id: p.id, qty: 24, unit_cost: Math.round(p.price * 0.84) })) });
    app.inventory.adjust(stockCtx, { product_id: products[21].id, location_id: loc.LEK, type: 'expired', qty: 6, reason: 'Past best-before date' });
    app.inventory.adjust(stockCtx, { product_id: products[25].id, location_id: loc.LEK, type: 'damage', qty: 2, reason: 'Crushed in delivery' });
    app.inventory.transfer(ctxFor('manager'), { from_location_id: loc.WHS, to_location_id: loc.IKJ, items: [{ product_id: products[0].id, qty: 20 }, { product_id: products[9].id, qty: 120 }], note: 'Weekly replenishment' });

    // refunds: a handful of next-day returns handled by the supervisor on lane 1
    for (const s of allSales.filter((_, i) => i % 97 === 5).slice(0, 6)) {
      const sale = db.get('SELECT * FROM sales WHERE id = ?', s.id);
      if (sale.status !== 'completed') continue;
      const pays = db.all(`SELECT method_code FROM payments WHERE sale_id = ? AND status = 'succeeded'`, s.id);
      if (!pays.every((p) => ['cash', 'ext_pos'].includes(p.method_code))) continue;
      const item = db.get('SELECT * FROM sale_items WHERE sale_id = ? ORDER BY line_total DESC LIMIT 1', s.id);
      const nextDay = addDays(localDate(new Date(s.t), tz), 1);
      if (nextDay >= today) continue;
      // supervisor refunds from a session on LEK-R03
      const t0 = new Date(localMidnightUtc(nextDay, tz).getTime() + 11 * 3600000 + rnd() * 3600000);
      at(t0);
      const sup = ctxFor('supervisor', 'LEK-R03');
      const open = app.sessions.current(sup) || app.sessions.open(sup, { opening_float: 2000000 });
      await app.refunds.create(sup, s.id, { items: [{ sale_item_id: item.id, qty: item.unit === 'each' ? 1 : item.qty, condition: rnd() < 0.5 ? 'resaleable' : 'damaged' }], reason_code: pick(['customer_return', 'damaged', 'wrong_item']), refund_method: 'original', manual_reference: 'REV' + Math.floor(rnd() * 99999), idempotency_key: `seed-ref-${s.id}` });
      cursor = new Date(cursor.getTime() + 3600000);
      app.sessions.close(sup, open.id, { counted_cash: app.sessions.figures(open.id).expected_cash });
    }

    // settlements for every past day (one with a simulated discrepancy), received funds, bank deposits
    const finance = ctxFor('finance');
    const ownerCtx = ctxFor('owner');
    for (let i = days; i >= 1; i--) {
      const d = addDays(today, -i);
      at(new Date(localMidnightUtc(addDays(d, 1), tz).getTime() + 9 * 3600000));
      for (const pc of ['sim-card', 'sim-transfer', 'sim-wallet']) {
        const batches = await sim(pc).fetchSettlements({ to: localMidnightUtc(addDays(d, 1), tz).toISOString(), timeZone: tz, simulateDiscrepancy: pc === 'sim-card' && i === 3 });
        for (const b of batches) {
          const r = app.settlements.importBatch(finance, pc, b, 'provider_api');
          if (i > 2 && r.status === 'matched') {
            cursor = new Date(cursor.getTime() + 5 * 3600000);
            app.payouts.confirmSettlementReceived(finance, r.id, { bank_reference: `STMT-${d.replace(/-/g, '')}-${pc.slice(4, 7).toUpperCase()}` });
          }
        }
      }
      // bank deposit of the day's safe drops (approved by owner)
      const drops = db.value(`SELECT COALESCE(SUM(cm.amount),0) FROM cash_movements cm WHERE cm.type = 'cash_drop' AND cm.created_at >= ? AND cm.created_at < ?`, localMidnightUtc(d, tz).toISOString(), localMidnightUtc(addDays(d, 1), tz).toISOString());
      if (drops && i > 1) {
        const safe = db.value(`SELECT id FROM financial_accounts WHERE code = 'SAFE-LEK'`);
        const bank = db.value(`SELECT id FROM financial_accounts WHERE code = 'BANK-OPS'`);
        const po = app.payouts.request(finance, { type: 'bank_deposit', amount: drops, source_account_id: safe, destination_account_id: bank, reason: `Cash deposit for ${d}` });
        cursor = new Date(cursor.getTime() + 3600000);
        app.payouts.transition(ownerCtx, po.id, 'approve', {});
        app.payouts.transition(finance, po.id, 'mark_paid', { reference: `DEP-${d.replace(/-/g, '')}` });
      }
    }
    // reconciliation for the last 3 closed days
    for (let i = 3; i >= 1; i--) { at(new Date(localMidnightUtc(addDays(today, -i + 1), tz).getTime() + 15 * 3600000)); app.reconciliation.run(finance, { business_date: addDays(today, -i) }); }
    // a supplier payment waiting for approval (segregation of duties demo)
    at(new Date(realNow.getTime() - 3 * 3600000));
    app.payouts.request(finance, { type: 'supplier_payment', amount: 48600000, destination_note: 'Dangote Foods Depot — invoice INV-DFD-88213', reason: 'Supplier invoice due', source_account_id: db.value(`SELECT id FROM financial_accounts WHERE code = 'BANK-OPS'`) });

    // today: Lane 2 has been trading since morning (session left open); Lane 1 is closed for you to open.
    await runDay(today, { isToday: true });
    setClock(null);
    db.exec('PRAGMA synchronous = FULL');
    const stats = db.get(`SELECT COUNT(*) AS sales, COALESCE(SUM(total),0) AS total FROM sales WHERE status IN ('completed','voided')`);
    app.log('info', `Demo history: ${stats.sales} sales, ₦${(stats.total / 100).toLocaleString('en-NG')} over ${days} days + today`);
  })().catch((e) => { setClock(null); db.exec('PRAGMA synchronous = FULL'); throw e; });
}

module.exports = { seedDemo, seedMinimal, ean13, PRODUCTS };
